ORB_SLAM3_RGB_ROS2:
  ros__parameters:
    robot_base_frame: base_link
    global_frame: map
    odom_frame: odom
    robot_x: 0.0
    robot_y: 0.0
    visualization: true
    ros_visualization: true
    # no_odometry_mode: false
    no_odometry_mode: true # Set to true if you don't have odometry

    # For pcl viz update
    map_data_publish_frequency: 1000 # publish every 1000.0 milliseconds
    landmark_publish_frequency: 1000 # publish every 1000.0 milliseconds (has no effect if ros_visualization is false)